version: "3.9"  # optional since v1.27.0
services:
#  web:
#    build: .
#    ports:
#      - "8000:5000"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
#    depends_on:
#      - redis
  database:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - data:/apps/mongo/data
    environment:
      - MONGODB_USERNAME=salasana
      - MONGODB_PASSWORD=salasana
      - MONGODB_DATABASE=test

volumes:
  data:
